# Generated by Django 6.0.3 on 2026-06-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('pay_period', models.CharField(max_length=50)),
                ('pay_date', models.DateField()),
                ('basic_salary', models.FloatField()),
                ('hra', models.FloatField()),
                ('income_tax', models.FloatField()),
                ('provident_fund', models.FloatField()),
                ('leave_days', models.IntegerField()),
            ],
        ),
    ]
