# Generated by Django 6.0.3 on 2026-06-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip_company_logo_payslip_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='updated_at',
        ),
    ]
