# Generated by Django 6.0.3 on 2026-06-06 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_payslip_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
