# Generated by Django 6.0.3 on 2026-06-15 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payslip_company_logo_alter_payslip_pay_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='payslip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='leave_days',
            field=models.FloatField(default=0),
        ),
    ]
